main: pw.xwy.prison_core.PrisonCore
name: PrisonCore
version: RELEASE
author: Xwy
authors: [Xaq]
depend: [Citizens]
commands:
  feed:
  mine:
    permission: xwy.admin.mine
    permission-message: §cYou do not have permission to do this!
  bal:
    aliases: [balance,money]
  scoreboardtoggle:
    aliases: [sbt,sbtoggle]
  ce:
    aliases: customenchants
  ds:
    aliases: [donorshop]
  rankup:
    aliases: [ru]
  kit:
  set:
    permission: xwy.admin.set
    permission-message: §cYou do not have permission to do this!
  spawn:
  chatstop:
    aliases: [cs,sc,stopchat]
    permission: xwy.admin.chatstop
    permission-message: §cYou do not have permission to do this!
  chatclear:
    aliases: [cc,clearchat]
    permission: xwy.admin.chatclear
    permission-message: §cYou do not have permission to do this!
  workbench:
    aliases: [wb]
    permission: xwy.perks.commands.workbench
    permission-message: §cYou do not have permission to do this!
  sellall:
    aliases: [sa]
    permission: xwy.perks.commands.sellall
    permission-message: §cYou do not have permission to do this!
  autosell:
    aliases: [as]
    permission: xwy.perks.commands.autosell
    permission-message: §cYou do not have permission to do this!